# Welcome to Jekyll!
#
#

title: Curtis J. Hu 
email: curtisjhu@berkeley.edu
tagline: My academic website
description: >- 
  Hello, I'm Curtis Hu. I'm an undergraduate at UC Berkeley doing Deep Learning with Particle Physics applications.
baseurl: ""
url: "https://curtisjhu.github.io"

google_analytics: G-BSXSV4N1YH

# Build settings
theme: minima
minima:
  date_format: "%b %-d, %Y"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

rss: rss
twitter_username: curtisjjhu
github_username:  curtisjhu
linkedin_username: curtisjhu
youtube_username: funnyscar

twitter:
  card: summary
  username: curtisjjhu

header_pages:
 - publications/index.md
 - projects/index.md
 - writings/index.md
 - archive/archive.md
#  - teaching/teaching.md
#  - talks.md

sass:
  quiet_deps: true

favicon: favicon.png
logo: favicon.png


# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
